// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkjgfxtfxucwmyolfznt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxramdmeHRmeHVjd215b2xmem50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjM3MDgsImV4cCI6MjA2MzczOTcwOH0.pr7OTO36D1tgaD-5rCe4gqKCjnS2huv43R_WCEi09i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);